// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMYSbdP6hO0mxdyVSkUgtB814vQYfKhJ4',
    appId: '1:404954467586:web:64c655ab6a64680d9b461b',
    messagingSenderId: '404954467586',
    projectId: 'latihanfirebase-ifcsg',
    authDomain: 'latihanfirebase-ifcsg.firebaseapp.com',
    databaseURL: 'https://latihanfirebase-ifcsg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-ifcsg.firebasestorage.app',
    measurementId: 'G-WE1WHFVV8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD415YHSDv16eTpjFJri3ljtaxKgEOXY_s',
    appId: '1:404954467586:android:4302fd5e1bc34ba39b461b',
    messagingSenderId: '404954467586',
    projectId: 'latihanfirebase-ifcsg',
    databaseURL: 'https://latihanfirebase-ifcsg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-ifcsg.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcs4vaY3yqvUaKKslXt4i7SMqFbFbmt10',
    appId: '1:404954467586:ios:36b4548b4a041d5a9b461b',
    messagingSenderId: '404954467586',
    projectId: 'latihanfirebase-ifcsg',
    databaseURL: 'https://latihanfirebase-ifcsg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-ifcsg.firebasestorage.app',
    iosBundleId: 'com.example.latihanfirebase',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcs4vaY3yqvUaKKslXt4i7SMqFbFbmt10',
    appId: '1:404954467586:ios:36b4548b4a041d5a9b461b',
    messagingSenderId: '404954467586',
    projectId: 'latihanfirebase-ifcsg',
    databaseURL: 'https://latihanfirebase-ifcsg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-ifcsg.firebasestorage.app',
    iosBundleId: 'com.example.latihanfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMYSbdP6hO0mxdyVSkUgtB814vQYfKhJ4',
    appId: '1:404954467586:web:bc098ad2deea701a9b461b',
    messagingSenderId: '404954467586',
    projectId: 'latihanfirebase-ifcsg',
    authDomain: 'latihanfirebase-ifcsg.firebaseapp.com',
    databaseURL: 'https://latihanfirebase-ifcsg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-ifcsg.firebasestorage.app',
    measurementId: 'G-RCK5P4D2KK',
  );
}
